version: '3'
services:

  mysql-server:
    image: mysql:5.7.22
    hostname: mysql-server
    container_name: database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
    networks:
      - mysql-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment: 
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: userpass
    networks:
      - mysql-net
    depends_on:
      - mysql-server
    ports:
      - "8085:80"

networks:
  mysql-net:
    driver: bridge
